import "./globals.css";
import Footer from "../../Component/Footer";
import Navbar from "../../Component/Navbar";
import Script from "next/script";

export const metadata = {
    title: "Travela",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" >
            <head>
                <meta charSet="utf-8" />
                <title>Travela - Tourism Website Template</title>
                <meta content="width=device-width, initial-scale=1.0" name="viewport" />
                <meta content="" name="keywords" />
                <meta content="" name="description" />
                {/* Google Web Fonts */}
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
                <link href="https://fonts.googleapis.com/css2?family=Jost:wght@500;600&family=Roboto&display=swap" rel="stylesheet" />
                {/* Icon Font Stylesheet */}
                <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" />
                <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />
                {/* Libraries Stylesheet */}
                <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet" />
                <link href="lib/lightbox/css/lightbox.min.css" rel="stylesheet" />
                {/* Customized Bootstrap Stylesheet */}
                <link href="css/bootstrap.min.css" rel="stylesheet" />
                {/* Template Stylesheet */}
                <link href="css/style.css" rel="stylesheet" />
            </head>

            <body>
                {/* <Navbar /> */}
                {children}
                {/* <Footer /> */}

                <div>
                    {/* JavaScript Libraries */}
                    <Script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js" strategy="beforeInteractive" />
                    <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" />
                    <Script src="lib/easing/easing.min.js" />
                    <Script src="lib/waypoints/waypoints.min.js" />
                    <Script src="lib/owlcarousel/owl.carousel.min.js" />
                    <Script src="lib/lightbox/js/lightbox.min.js" />
                    {/* Template Javascript */}
                    {/* <Script src="js/main.js" /> */}
                    <Script src="js/main.jsx" strategy="afterInteractive" />
                </div>

            </body>
        </html>
    );
}